### ISSUE TITLE
Intranet theme mockups

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#1]
Hi Eric,
Here are some mock ups of the intranet theme. Basically we would love a simple template with an area to put the logo and a header image across the top and a side navigation to the left. These are my wish list items, but if we have to pick and choose things because of time/budget we can do that and go from there. As far as the styling, any of these items that fall outside the original scope of the project we would like to use our weekly time to complete if that's ok? Dotty my boss has used all of the web funds until our new fiscal year begins on July 1.

**DASHBOARD PAGE:** [sample](http://newsletter.jccmi.edu/intranet/mock-up/intranet.jpg)
- area where we can highlight news/announcements on the dashboard page and then link to the announcements page for a listing of all announcements (similiar to the news plugin for our main site where we have 3 featured and then link to the main news page)
- area where we can pull in up coming events and then link to an events calendar (similar to main site)
- area where we can pull in latest discussions from the forum page
- 6 quick link boxes
- optional alert for breaking news/special events (similar to main site)

**ANNOUNCEMENTS:** [sample](http://newsletter.jccmi.edu/intranet/mock-up/announcements.jpg)
- This would be where the main listing of the news/announcements would go. I would also like to have some sort of archive listing for past announcements. Also would like the option to feature 3 on the main dashboard page and if possible tag departments. So for instance if there is an announcements Human Resources related it would be nice for that to show up on the HR department page.

**DEPARTMENTS:** [sample](http://newsletter.jccmi.edu/intranet/mock-up/departments.jpg) [child page menu sample](http://newsletter.jccmi.edu/intranet/mock-up/departments-hr.jpg)
- So I'm not sure if this is even possible, but I was thinking of a way that I can put a lot of information on one page. So on the sample I was thinking this would work kind of the same as the site section menus where each department could have a menu and then when you clicked a box that information would populate in the below content area. The main frustration I get around here is that there are so many pages so it would be nice to be able to include a whole bulk of different topics all on one page. Also, if there is a way we can include any tagged forms/announcements? 

**DISCUSSION:** 
- I don't have a sample of this one because I'm not really sure how this would work. Is there a way we can incorporate a forum or message board where employees can create topics and threads? The one thing everyone was looking forward to with the intranet was the ability to collaborate with each other and have discussions aside from e-mail.

**EMPLOYEE DIRECTORY** [sample](http://newsletter.jccmi.edu/intranet/mock-up/directory.jpg)
- This is the listing from our main website directory staff plugin...I would like to incorporate a search feature if possible and change the styling a little.

**FORMS** [sample](http://newsletter.jccmi.edu/intranet/mock-up/directory.jpg)
- This is where we would house all of our forms in a table like format. I would love the ability to be able to tag them and disperse through the department pages if possible.

Let me know if I'm way off the mark here with the ability to do any of these things! I want to be courteous of your schedule as well. Let me know if you have any questions as all.

**Comment by BigActual** [comment]
@banksashleym - May I close this issue?

**Comment by banksashleym** [comment]
Yes, sure can!
