### ISSUE TITLE
resize and move feature image on blog posts

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#13]
Is it possible to move the featured image spot on the blog posts? The height isn't very tall and for those images I am using a rectangle image so there is a lot that gets blown up and cropped. Would it be possible for just the blog pages have the featured image maybe float to the right of the content?

But then I would still like to include the "header image" at the top of the pages like the rest of the pages. 

![sample](https://user-images.githubusercontent.com/15264315/56054748-a383ae80-5d25-11e9-8bec-99e31953744c.jpg)

**Comment by d4mation** [comment]
While working on #14 I went ahead and did this as they're fairly related 👍

**Comment by banksashleym** [comment]
This is awesome, thanks!
