### ISSUE TITLE
Pull Employee Directory from jccmi.edu

### ISSUE THREAD

**Issue by d4mation** [JacksonCollege/jc-intranet-theme#15]
Since the database is "shared", we could pull this data from jccmi.edu and thereby only have one place to manage this rather than two.

**Comment by banksashleym** [comment]
Yes, that would be great!

**Comment by d4mation** [comment]
This change is now Live :+1:

All the Employee information on the Intranet is now pulled from the same database as jccmi.edu. On the Intranet, it still shows their phone numbers and emails but that information is still hidden on jccmi.edu.

Clicking the little Edit icons on the Intranet also will take you directly to jccmi.edu to edit them.

**Comment by d4mation** [comment]
Well, the edit buttons did work just a second ago... I'll re-open and look into this. I have an idea as to the cause.

**Comment by d4mation** [comment]
There we go, now it is fixed :+1:

**Comment by banksashleym** [comment]
This is amazing, I so appreciate it :)
