### ISSUE TITLE
Users/Roles

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#18]
Hi Eric,
I just had a question about users of the intranet. Will everyone that logs into the intranet through the adfs login screen then also be created as a user in Wordpress? I have sent the link out to everyone in Marketing, and then went to "users" in wordpress and noticed that everyone is now created as a user at the super admin level. Is it possible that our employees log into the intranet just to view the content and not be able to access the back end of everything in Wordpress?

Either that, or could we remove the editing toolbar when logged in so they don't know they have access to anything?! lol :)

I just went into my user account and disabled the editing toolbar and this would be just fine - if we could disable it from all users that would be great.

Thanks!

**Comment by d4mation** [comment]
They are created as Users, yes. They are created as Subscriber-level users. This is a requirement for WordPress to function properly, so they cannot log in without a User being created. 

They should not be able to Edit anything as Subscribers though. Do you mean just the black bar itself? We could hide that for Subscribers.

**Comment by banksashleym** [comment]
Yes that would be great if we could hide the black bar for any new users. Thanks!

**Comment by d4mation** [comment]
Any Subscriber Level Users (Basically anyone without the ability to Edit Posts) will now no longer see the Admin Bar.

Note: This also effects Super Admins who have not been granted a specific Role on the Intranet Site. If these Super Admin users should be able to see the Admin Bar, they will need to be made into "Local Administrators" by editing their Local User on the Intranet Site to be an Admin.

**Comment by banksashleym** [comment]
Sounds good, thank you!
