### ISSUE TITLE
Add shortcodes to intranet site

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#2]
Hello! Is it possible to add the following shortcodes that I use on the main site to the intranet site? 

- tabs
- columns
- faq (I enabled the FAQ plugin but the shortcode isn't working)

Thanks!

**Comment by d4mation** [comment]
These shortcodes exist as part of the Base Theme, which the Intranet Theme extends. These should work.

Were you trying these on the Live Intranet site? Until just a minute ago, the Live Intranet site did not use the Intranet theme.

**Comment by banksashleym** [comment]
Great, thank you! They are working now :)
