### ISSUE TITLE
two header images on forum page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#22]
Hello! I believe we are going to launch the intranet to our employees today. I just noticed that there are two header images that show up on the [Forums ](https://intranet.1.jccmi.edu/forums/)page. Is there a way we could remove one of those? Thanks!

**Comment by d4mation** [comment]
Hmmm, this doesn't happen in my local environment. I see you installed some styling plugins for bbPress. I'll take a look and see if those are the cause and try to find a work-around.

**Comment by banksashleym** [comment]
thanks!
