### ISSUE TITLE
Deploy from live to staging

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#26]
I have a few requests on the intranet and the main website that i would like to test out on staging. Could we update the staging site to reflect the live site? Thanks!

**Comment by d4mation** [comment]
I've gone ahead and deployed from Live to Staging.

Note: This possibly could make the login via your Active Directory credentials no longer work properly on Staging. If so, you can use the URL that you had found in #25 but adjusted to point to the Staging site. (So, https://jccmi.edu would be swapped out for http://jacksoncollege.staging.wpengine.com)

**Comment by d4mation** [comment]
If Active Directory stuff no longer works on Staging, I made a backup of Staging beforehand so we can retrieve those settings 👍

**Comment by banksashleym** [comment]
Thanks Eric!
