### ISSUE TITLE
Add Font Awesome CSS

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#3]
Would it be possible to also add the FontAwesome icon library CSS file like the main site has as well? I discussed the [department pages](http://newsletter.jccmi.edu/intranet/mock-up/departments.jpg) with Steve last week and for the time being I can build these out as buttons vs creating and styling an independent sub menu for each department page.

Thanks!

**Comment by d4mation** [comment]
Yep, I have actually already added it!

It uses Font Awesome v5 which has slightly different icon names, in case you've been adding them manually.

https://fontawesome.com/icons

https://github.com/JacksonCollege/jc-intranet-theme/blob/8c355f7e1d9fb678846abe1ac62380b578780f51/functions.php#L61-L68
