### ISSUE TITLE
TinyMCE removing span elements when switching to visual

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#4]
Hi Eric,
After talking with Steve, we thought that it was best to do a workaround for our department pages where I could create a "menu" and place it on each page ([sample link](https://intranet.1.jccmi.edu/faculty/human-resources/benefits/))...Anyway, I have finalized the styling, but I notice when i switch from html to the visual tab to start adding content to the page it strips out the <span> styling i have around the icon. I found [this article](https://gist.github.com/tylerforret/d383b9af6b43e64293ad9d582ece475b)...would it be possible to place this code into site or if you know of a better workaround so that it doesn't strip out the <span> tags that would be great.

Thanks!

**Comment by d4mation** [comment]
@banksashleym 

It seems that the Editor doesn't explicitly remove `<span>` tags. It only removes ones that have no content inside of them.

If you place a `&nbsp;` anywhere inside of your `<span>` tag, it will prevent it from being removed when you swap between the Visual and Text tabs.

Can you give that a shot and make sure that it doesn't cause any weird spacing problems? If it does, I'll see if I can find a different solution. The code you found does not make a difference, unfortunately. 

Example: ` <span class="css-button-icon"><i class="fa fa-gear" aria-hidden="true">&nbsp;</i></span>`

**Comment by banksashleym** [comment]
Great, thank you!

And thanks for the tip! I was playing around with that originally, and is there a way with the columns shortcode that instead of stacking them on tablet/mobile that they could convert down to three columns insead of 6?

**Comment by banksashleym** [comment]
Nevermind, I'm dumb!! I just realized you can add different sizes to the column as you wrote above...wow, mind blown I had no idea you could do that :)

THANK YOU SO MUCH!

**Comment by d4mation** [comment]
Yep! You can find the full documentation here: https://foundation.zurb.com/sites/docs/grid.html

So, what you could do is this:

```
[row]
[column sizes="small-4 medium-2"]
This is 1/6 of the full row size on Medium (Tablet) upward and 1/3 of the full row on Small (Mobile)
[/column]
[/row]
```

Note: `medium` is Tablet and by not defining a `large` Size, that means it inherits the `medium` size. 

It is a 12 column grid system, so to determine the column size you can just divide 12 by the number of columns you want at that size. So, 12 / 3 = 4.

You can do a lot of other crazy things with `push` and `pull` classes as well in order to reorder columns based on screen size too.

---

You're welcome! Let me know if that `&nbsp;` trick works.

**Comment by banksashleym** [comment]
Thanks!! I'm going to check that out. And yes, the &nbsp; trick worked :)

**Comment by banksashleym** [comment]
whoops lol `&nbsp;`
