### ISSUE TITLE
only some icons are showing

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#5]
Hello! I'm styling my department buttons and I've noticed that only some icons are coming through? I'm using the free/solid version for all of them, but about half are coming through at a question mark?

[Human Resources Page example](https://intranet.1.jccmi.edu/departments/human-resources/)

**Comment by d4mation** [comment]
Font Awesome v5 uses different Class Names than v4 did (Why they did that, I don't know) so you have to update those to match what Font Awesome v5 expects.

I linked the list of Icons here: https://github.com/JacksonCollege/jc-intranet-theme/issues/3#issuecomment-477241703

You can search for the same icons you're using now and if you click them, at the top of the screen it will tell you the updated class names.

For example, `fa fa-file-medical` should instead be `fas fa-file-medical`

**Comment by banksashleym** [comment]
Hm, that's weird because those are the names I was using? I found each icon on the website and copied the file name. Some of them work and some don't?

**Comment by d4mation** [comment]
Huh

**Comment by d4mation** [comment]
Just pushed a fix for this. If you hard-refresh all of your icons should show correctly now 👍

**Comment by banksashleym** [comment]
Perfect, they're working :) Thank you!
